### ISSUE TITLE
Video remaining time doesn't take into account for trimmed videos

### ISSUE THREAD

**Issue by Deanbau** [phuvf/oscpoint#56] opened 2024-09-18 00:29 UTC
When you trim a video in PowerPoint, OSCPoint disregards the trimmed portions and continues to display the duration and remaining time of the original, unedited video.

**Comment by phuvf** [comment] 2024-09-18 12:11
Closing, as duplicate of #23

**Closed by phuvf** 2024-09-18 12:11 UTC
