### ISSUE TITLE
ShowState not updating after Ending the PP

### ISSUE THREAD

**Issue by helex1** [phuvf/oscpoint#47] opened 2024-06-12 19:50 UTC
When I use the End-buttotn the Show-state remains red instead of returning to green.
![OSC-Point-01](https://github.com/phuvf/oscpoint/assets/52051323/480fbb5a-5e4b-4136-9aa3-987628d56777)
[2024-06-12_oscpoint.log](https://github.com/user-attachments/files/15810204/2024-06-12_oscpoint.log)

**Comment by helex1** [comment] 2024-06-12 19:52
When I close the Powerpoint-file it returns to green.

**Comment by helex1** [comment] 2024-06-12 19:56
[LT-LEX_companion_log_20240612-2154.csv](https://github.com/user-attachments/files/15810262/LT-LEX_companion_log_20240612-2154.csv)
Here the Companion Log

**Comment by phuvf** [comment] 2024-06-16 17:44
Think this was caused by media feedbacks not resetting properly on slide show end. Fixed in v2.1

**Closed by phuvf** 2024-06-16 17:44 UTC
Labels: bug
